### PR TITLE
corrected text in PG footer for RST

### PR DESCRIPTION
**Pull request by asylumcs**

### CODE REVIEW

**Comment by gbnewby** [comment]
Yes, it's important for footers to match. In conversations with Roger Frank, we see that insertion of <h*> tags can be problematic for the ebookmaker table of contents.

It's desirable to have a TOC entry for the full PG license, but not subheadings.

I'd like to work to have (a) the same header/footer style & content, regardless of RST v. HTML v. text, and for all derived formats; and (b) the start of the footer in the TOC in epub/mobi (something like, "Project Gutenberg License").

It may be possible to automated headers+footers as part of the processing chain that happens on ibiblio (i.e., at the time a set of files is pushed). We can discuss this whenever you are ready.

**Comment by eshellman** [comment]
did you mean to close this PR @gbnewby ?

**Comment by gbnewby** [comment]
No. I made a comment and it still said my comment was open.

**Comment by eshellman** [comment]
can be confusing

**Comment by eshellman** [comment]
I am in the process of implementing Greg's suggestions above. The resulting code will use this corrected file for the generated HTML, version of books produced from rst source files, but the header and footer will be stripped and replaced by boilerplate formatted for EPUB and inserted into the spine after the ToC is generated.

**Comment by gbnewby** [comment]
Excellent! Thanks for working on that.

Is it reasonable to do the same thing (paste a standard footer; sane TOC)
for epub & mobi generated formats, as well?

**Comment by eshellman** [comment]
This will effect only epub and mobi generated files

**Pull request merged**
