### PR TITLE
Add MacOS instructions

### PR DESCRIPTION
**Pull request by cpeel**
Getting ebookmaker working with MacOS is pretty easy with Homebrew.

### CODE REVIEW

**Comment by eshellman** [comment]
There are many issues installing python on MacOS. I would prefer to link the user someplace else. In particular, it's bad advice to install ebookmaker without creating a virtual environment. It's also bad advice to recommend fiddling with the user's PATH - pipenv does that safely for you. Which is why I use pipenv on both linux and mac.

You've also recommended installing Py3.7, which, while it works with ebookmaker, it's not in our testing.

**Comment by cpeel** [comment]
That's fine. I can incorporate these instructions into the Guiguts manual.

Note that Homebrew installs a separate python instance and places installed modules outside the system python. Installing python modules at a system level with sudo is bad -- which is why we use `--user` in pip to install to a separate location. There's nothing wrong with having a user change their path to point to scripts elsewhere -- they're just scripts. I also professionally develop on Linux and MacOS and use pipenv when we need porcelain environments but we don't use it for everything (it isn't as though you installed pip in a pipenv, for instance).

Feel free to close this MR.

**Comment by eshellman** [comment]
https://xkcd.com/1987/

**Comment by eshellman** [comment]
Thanks for your work on guiguts. Although I think I've removed all the things in 6 year old ebookmaker/libgutenberg that made it dangerous to run in the same environment as other programs, there's code I've still not looked at. Ebookmaker historically assumed that it owned the python environment. 

If you think it's a good idea to have a separate set of instructions for running with guiguts, that would be great. I run and develop py3 stuff only with pipenv, and do installs from pypi.

**Pull request closed without merging**
