### PR TITLE
Updates to HtmlTemplates.py

### PR DESCRIPTION
**Pull request by gbnewby**
Reworked HtmlTemplates.py so we can more easily extract headers for other consumers. No functional changes.

### CODE REVIEW

**Comment by eshellman** [comment]
better to branch off v12  (dev) branch. Not clear what you are trying to do.

**Comment by gbnewby** [comment]
Done. I don't see what conflict it is complaining about, though - can you identify & resolve?

The purpose is to expose plain strings (variables) that can be used by dopush and workflow, on the pglaf.org server. 

There might be a few more further changes to expose more of the HTML header material. Basically, my goal is to have static variables containing plain strings exposed to other consumers of the module. That way, they can be extracted very easily, without for example needing to supply an entire 'dc' object to populate the non-static variables.

**Comment by eshellman** [comment]
deconflict looks reallu hard, suggest to start over. the 
maybe the plain text with boilerplate will be what you want - I implemented that today, almost ready to commit to v12

**Comment by gbnewby** [comment]
Are you substantially done with v12 edits to HtmlTemplates.py? If so I'll apply those changes... if you're still working with it, I can wait. The changes involved a lot of lines, but almost no logic or procedural changes.

**Comment by eshellman** [comment]
yes. just remember the same template needs to work for txt, html and epub presentation on a variety of screen sizes. So for example, I had to add whitespace to get the txt to look right. And that's why there's no css in the templates.

**Comment by eshellman** [comment]
ok. Avoid putting CSS in the template as you seem to have done for #189  as we'll likely need to tweak for pdf

**Comment by eshellman** [comment]
@gbnewby OK, I think I understand what you want. you want headera, headerb, headera_copy and headerb_copy to be importable strings. I can make that change quickly. I'm not sure why you use re.sub instead of f-strings, but I'm guessing your python is pre-3.6?

**Comment by eshellman** [comment]
closed in favor of #c5631d761627257f403188f8dee925b5cb61dfb8

found a bug in some other stuff so no release today

**Pull request closed without merging**
