### PR TITLE
Remove libgutenberg from Pipfile

### PR DESCRIPTION
**Pull request by cpeel**
Load libgutenberg from ebookmaker's requires list in `setup.py` rather than specifying a version in the Pipfile. This ensures that the version we use in development matches the version the package uses.

And of course anytime we touch `Pipfile`, pipenv revs all packages <sigh>.

Frankly, given that the Pipfile is only needed for development. It would probably be better to remove `Pipfile.lock` from the repo entirely and add the file to `.gitignore`. This will prevent persisting an outdated lock file that doesn't fully reflect changes to `setup.py`. `pipenv install` will happily install from `Pipfile`.

### CODE REVIEW

**Comment by eshellman** [comment]
the pipfile change I'm ok with; I need to think about the lock file - it allows us to reproduce and share an environment when things get screwed up, and I don't think reproducing YOUR environment is useful for us. but keeping it out of the repo, I can see that

**Comment by eshellman** [comment]
I guess I'd prefer to add pipenv.lock to .gitignore

**Comment by cpeel** [comment]
That makes sense to me. I can do that in this MR or you're welcome to close this MR and do the changes yourself (so you can copy off your `Pipfile.lock` before you `git rm` it out).

**Comment by eshellman** [comment]
either way is fine with me.

**Comment by eshellman** [comment]
prefer you do it so we pick up your improvement to pipfile

**Pull request merged**
